### ISSUE TITLE
Save user account to disk

### ISSUE THREAD

**Issue by kernelkind** [damus-io/android#110]
A user's account (#111) should be able to be saved to the disk. This will be invoked after the user adds their account using #3. This issue will allow easy account retrieval on future app opens in #112.

Validation:
- can save a user account on Windows
- can save a user account on linux
- can save a user account on macos
- can save a user account on android

**Comment by jb55** [comment]
Duplicate of:

- https://github.com/damus-io/notedeck/issues/66
